services:
  frontend:
    container_name: ${PROJECT_NAME}_react_frontend
    build: ./frontend
    restart: always
    command: "npm run dev"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    env_file: "./frontend/.env"

  fastapi_server:
    container_name: ${PROJECT_NAME}_fastapi_server
    build: 
      context: ./backend
      dockerfile: backend/Dockerfile
    restart: always
    command: "sh -c 'gunicorn -w 3 -k uvicorn.workers.UvicornWorker app.main:app  --bind 0.0.0.0:8000 --preload --log-level=debug --timeout 120'"
    volumes:
      - ./backend/backend/app:/code
    ports:
      - "8000:8000"
    env_file: "./backend/.env"

  caddy_reverse_proxy:
    container_name: ${PROJECT_NAME}_caddy_reverse_proxy
    image: caddy:alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - .env
      - ./backend/.env
    volumes:
      - ./backend/caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

  mongodb:
    image: mongo:latest
    container_name: ${PROJECT_NAME}_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  caddy_data:
  caddy_config:
  mongodb_data:
